language: node_js
env:
  - PGDATABASE=foodfast_test
  - PGUSER=postgres
  - PGHOST=localhost
  - PGPASSWORD=
  - PGPORT=5432
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database foodfast_test;' -U postgres
  - npm run createTable
before_install:
  - npm install coveralls
after_script:
  - npm run coverage
