language: node_js
env:
  - PGUSER=postgres JWT_KEY="danielisagoodboy" TOKEN1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMkBmb29kZmFzdC5jb20iLCJ1c2VyaWQiOjEsImlhdCI6MTUzOTYzMjk4MX0.SDril3sLKm2M3qSf9aDrYl1t40XnQpHDGgHQp9urq2A TOKEN2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhbmllbHNob2l0QGdtYWlsLmNvbSIsInVzZXJpZCI6MiwiaWF0IjoxNTM5NjMyNzU3fQ.9SSwr6jF4u0uO4iAdmFgngqlcOBEj1ND1aNItOpiSOg
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database foodfast_test;' -U postgres
  - npm run build
  - npm run table
before_install:
  - npm install coveralls
after_script:
  - npm run coverage
