language: node_js
env:
  - PGUSER=postgres JWT_KEY="danielisagoodboy"
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database foodfast_test;' -U postgres
  - npm run build
  - npm run table
before_install:
  - npm install coveralls
after_script:
  - npm run coverage
