language: node_js
env:
  - PGDATABASE=foodfast
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - export PGUSER=postgres
  - export PGHOST=localhost
  - export PGPASSWORD=
  - export PGPORT=5432
  - psql -c 'create database foodfast;' -U postgres
  - npm run createTable
before_install:
  - npm install coveralls
after_script:
  - npm run coverage
