language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c "create database foodfast if not exists;" -U postgres
  - psql -c "CREATE USER Danielshow WITH PASSWORD '';" -U postgres
  - npm run createTable
before_install:
  - npm install coveralls
after_script:
  - npm run coverage
